name: Daily RIA Leads

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"  # runs daily at 13:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r src/src/requirements.txt

      - name: Run script
        run: python src/src/main.py
